#!/bin/bash

if [ "$CC_SITE" = "docs-ui" ]; then
    echo "Building Pagefind Component UI documentation"
    # Build main docs site first (needed for search index)
    cd docs && npm i && hugo
else
    export HUGO_PAGEFIND_DOCS_VERSION=$(node ./.backstage/set_version.cjs)
    echo "Building documentation for $HUGO_PAGEFIND_DOCS_VERSION"
    cd docs && npm i
fi
